version: v1.1.0

oauth2_provider:
    url: "http://hydra:4445"
log:
    level: debug
    format: text
    leak_sensitive_values: true
dsn: memory
serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: True
  admin:
    base_url: http://kratos:4434/

identity:
    default_schema_id: default
    schemas:
        - id: default
          url: file:///etc/config/kratos/identity.schema.json
session:
  whoami:
    required_aal: highest_available

selfservice:
    allowed_return_urls:
      - http://localhost:4455/ui/
    default_browser_return_url:
        http://localhost:4455/ui/
    flows:
        error:
            ui_url: http://localhost:4455/ui/error
        login:
            ui_url: http://localhost:4455/ui/login
        recovery:
            enabled: True
            ui_url: http://localhost:4455/ui/reset_email
            use: code
            after:
                default_browser_return_url: http://localhost:4455/ui
                hooks:
                    - hook: revoke_active_sessions
        settings:
            # TODO: Replace with self-service settings page when implemented
            ui_url: http://localhost:4455/ui/reset_password
            required_aal: highest_available
            after:
                webauthn:
                    default_browser_return_url: http://localhost:4455/ui/setup_passkey
        registration:
            ui_url: http://localhost:8080/some/path/ui/registration_error
            after:
                oidc:
                    hooks:
                    - hook: web_hook
                      config:
                        url: http://host.docker.internal:8080/api/v0/verify
                        body: base64://ZnVuY3Rpb24oY3R4KSB7CiAgZW1haWw6IGN0eC5pZGVudGl0eS50cmFpdHMuZW1haWwKfQ==
                        method: POST
                        emit_analytics_event: true
                        response:
                          ignore: false
                          parse: true
                        auth:
                          type: api_key
                          config:
                            name: Authorization
                            value: secret_api_key
                            in: header
                    - hook: session
                webauthn:
                    hooks:
                    - hook: session
    methods:
        totp:
            enabled: true
            config:
                issuer: Identity Platform
        lookup_secret:
            enabled: true
        password:
            enabled: True
            config:
                haveibeenpwned_enabled: false
        code:
            enabled: True
        webauthn:
            enabled: True
            config:
                passwordless: True
                rp:
                    # Set 'id' to the top-level domain.
                    id: localhost
                    # Set 'origin' to the exact URL of the page that prompts the user to use WebAuthn. You must include the scheme, host, and port.
                    origins:
                        - http://localhost:4455
                    display_name: Canonical
        oidc:
            enabled: True
            config:
                providers:
                - id: "github"
                  provider: "github"
                  mapper_url: "file:///etc/config/kratos/schema.jsonnet"
                  scope: ["user:email"]
                  label: Github
courier:
    smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
