name: container scan
run-name: Scanning container ${{ inputs.image }} to ghcr.io/canonical/user-verification-service

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
        description: "image to scan"
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload scan results to GitHub
        uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5 # v3
        with:
          sarif_file: 'trivy-results.sarif'
