name: Report UI Coverage
on:
  workflow_run:
    workflows: ["UI"]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: coverage
          run-id: ${{ github.event.workflow_run.id }}
          path: "./ui/coverage"
      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@v2
        with:
            working-directory: "./ui"
            name: "UI Test Coverage"
